name: Publish

on:
  push:
    branches: [main]
  repository_dispatch:
    types:
      - sync-read-model
  workflow_dispatch:

permissions: write-all

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Auth blog miyamo today
        run: exit 0

      - name: Restore Gatsby cache
        id: cache-primes-restore
        uses: actions/cache/restore@v4
        if: ${{ github.event.action ==  'sync-read-model' }}
        with:
          path: |
            ./.cache
          key: ${{ runner.os }}-gatsby-build

      - name: Build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BLOG_API_MIYAMO_TODAY_URL: ${{ secrets.BLOG_API_MIYAMO_TODAY_URL }}
          BLOG_API_MIYAMO_TODAY_TOKEN: ""
          GITHUB_API_TOKEN:  ${{ secrets.READ_MY_REPO }}
          FACEBOOK_APP_ID: ${{ secrets.FACEBOOK_APP_ID }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        run: bun run build

      - name: Save Gatsby cache
        uses: actions/cache/save@v4
        with:
          path: |
            ./.cache
          key: ${{ runner.os }}-gatsby-build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: bun run deploy