name: Publish

on:
  push:
    branches: [main]
  repository_dispatch:
    types:
      - sync-read-model
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions: write-all

jobs:
  publish:
    runs-on: ubuntu-24.04-arm
    services:
      qdrant:
        image: qdrant/qdrant:latest
        ports:
          - "6333:6333"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bun install

      - name: Set up aws cli
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
          mask-aws-account-id: true

      - name: Auth blog miyamo today
        id: auth-blog-miyamo-today
        run: |
          ID_TOKEN=$(aws cognito-idp admin-initiate-auth --user-pool-id ${{ secrets.USER_POOL_ID }} --client-id ${{ secrets.USER_POOL_CLIENT_ID }} --auth-flow "ADMIN_USER_PASSWORD_AUTH" --auth-parameters USERNAME=${{ secrets.COGNITO_USER_NAME }},PASSWORD=${{ secrets.COGNITO_PASSWORD }} --query "AuthenticationResult.IdToken" | sed 's/"//g' | sed '/^$/d')
          echo "::add-mask::$ID_TOKEN"
          echo "idtoken=${ID_TOKEN}" >> $GITHUB_OUTPUT

      - name: Restore Gatsby cache
        id: cache-primes-restore
        uses: actions/cache/restore@v4
        if: ${{ github.event.action ==  'sync-read-model' }}
        with:
          path: |
            ./.cache
          key: ${{ runner.os }}-gatsby-build-${{ github.sha }}-${{ github.event.client_payload.event_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-${{ github.sha }}-

      - name: Build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BLOG_API_MIYAMO_TODAY_URL: ${{ secrets.BLOG_API_MIYAMO_TODAY_URL }}
          BLOG_API_MIYAMO_TODAY_TOKEN: ${{ steps.auth-blog-miyamo-today.outputs.idtoken }}
          GITHUB_API_TOKEN: ${{ secrets.READ_MY_REPO }}
          FACEBOOK_APP_ID: ${{ secrets.FACEBOOK_APP_ID }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.ALGOLIA_SEARCH_KEY }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          GATSBY_ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
          GATSBY_CPU_COUNT: 2
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: bun run build

      - name: Save Gatsby cache
        uses: actions/cache/save@v4
        with:
          path: |
            ./.cache
          key: ${{ runner.os }}-gatsby-build-${{ github.sha }}-${{ github.event.client_payload.event_id }}

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: bun run deploy

      - name: Invalidate CloudFront Edge Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
